# https://taskfile.dev

version: '3'

vars:
  PROJECT_NAME: Torwell84-V2

tasks:
  default:
    cmds:
      - task: --list-all

  setup:
    desc: "Install all frontend and backend dependencies."
    cmds:
      - bun install

  dev:
    desc: "Starts the application in development mode with hot-reloading."
    cmds:
      - bun tauri dev --features experimental-api

  build:
    desc: "Builds the application for production."
    cmds:
      - bun tauri build --features experimental-api

  mobile:android:
    desc: "Build the Android app using Capacitor"
    cmds:
      - ./mobile/scripts/build_android.sh

  mobile:ios:
    desc: "Build the iOS app using Capacitor"
    cmds:
      - ./mobile/scripts/build_ios.sh

  mobile:release:
    desc: "Build Android and iOS apps and collect artifacts"
    cmds:
      - task mobile:android
      - task mobile:ios
      - mkdir -p mobile/dist
      - cp mobile/android/*.apk mobile/dist/ 2>/dev/null || true
      - cp mobile/ios/*.ipa mobile/dist/ 2>/dev/null || true

  release:
    desc: "Build MSI/DEB/DMG packages for the current platform"
    cmds:
      - ./scripts/build_release.sh
