blank_issues_enabled: false
contact_links:
  - name: Security Disclosure
    url: https://github.com/Torwell/security
    about: "Report security vulnerabilities confidentially."
default:
  labels:
    - triage
  title: "[Task]: "
